name: weak_collections
description: Collection of soft references.
version: 1.0.0
repository: https://github.com/aymtools/weak_collections

environment:
  sdk: '>=2.17.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
